FROM python:3.11

WORKDIR /app

RUN pip install --upgrade pip setuptools wheel

# Install PyTorch CPU from official index
RUN pip install torch --index-url https://download.pytorch.org/whl/cpu

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
